export global Info {
    in-out property <string> processor: "AMD 5950x";
    in-out property <int> logical_cpu_processors: 32;
    in-out property <int> memory_capacity_mib: 61035;
    in-out property <string> graphics_processor: "Nvidia RTX 3090";
    in-out property <int> logical_gpu_processors:  10496;
    in-out property <string> os: "Windows 10 Home";
    in-out property <[int]> top_personal_runs: [20, 15, 10, 5];
    in-out property <[string]> recommended_mod_list: ["Lithium", "ScalableLux", "C2me", "FerriteCore"];
    in-out property <[bool]> recommended_mods_toggle: [true, true, true, true];
    in-out property <[string]> jvms: ["Azul", "Adoptium", "Graalvm"];
    in-out property <[bool]> jvms_toggle: [true, true, true, true];
    in-out property <[string]> gcs: ["Z", "Shenandoah", "G1", "Parallel"];
    in-out property <[bool]> gcs_toggle: [true, true, true, true];
    in-out property <[string]> args: ["UseCompactObjectHeaders", "LargePages"];
    in-out property <[bool]> args_toggle: [true, true];
    in-out property <int> ram_alloc: 1;
}