import { BasicScreen } from "basic_screen.slint";
import { Info } from "global_info.slint";
import { ProgressIndicator, CheckBox, ScrollView, Slider, Button } from "std-widgets.slint";
import { SeparatorLine } from "separator.slint";
export component MainMenu inherits BasicScreen {
    in-out property <string> processor_name;

    // Left Panel
    left := Rectangle {
        width: 40%;
        height: 100%;
        x: 20px;

        // Logo
        logo_box := Rectangle {
            width: 100%;
            height: 15%;
            border-color: lightgray;
            border-width: 2px;
            border-radius: 10px;
            y: 30px;
            Image {
                source: @image-url("icon.png");
                height: 100%;
            }
        }

        // Specs
        specs := Rectangle {
           width: 100%;
           height: 20%;
           border-color: lightgray;
           border-width: 2px;
           border-radius: 10px;
           y: 45px + logo_box.height;

           sys_text := Text {
                text: "System";
                font-size: 12pt;
                y: 15px;
           }

           VerticalLayout {
                y: sys_text.height + 20px;
                x: 5px;
                alignment: start;
                max-height: specs.height - sys_text.height;
                spacing: 5px;
                Text {
                    text: "Processor: " + Info.processor + " (" + Info.logical_cpu_processors + ")";
                }
                Text {
                    text: "Graphics Processor: " + Info.graphics_processor + " (" + Info.logical_gpu_processors + ")";
                }
                Text {
                    text: "Memory: " + Info.memory_capacity_mib + "MiB";
                }
                Text {
                    text: "OS: " + Info.os;
                }
           }
        }

        // Top Runs
        Rectangle {
           width: 100%;
           height: 50%;
           border-color: lightgray;
           border-width: 2px;
           border-radius: 10px;
           y: 60px + logo_box.height + specs.height;

           rank_text := Text {
                text: "Personal Ranking";
                y: 15px;
                font-size: 12pt;
           }

           VerticalLayout {
                y: rank_text.height + 20px;
                alignment: start;
                spacing: 10px;
                for i in Info.top_personal_runs: Rectangle {
                    pb := ProgressIndicator {
                        progress: i / Info.top_personal_runs[0];
                        width: 90%;
                        preferred-height: 20px;

                    }

                    Text {
                        text: i;
                        x: pb.x + 10px;
                        color: black;
                    }
                }
           }
        }
    }

    // Right Panel
    Rectangle {
        width: 50%;
        height: 90%;
        x: left.width + left.x + 30px;
        border-color: lightgray;
        border-width: 2px;
        border-radius: 10px;

        Text {
            text: "Benchmark";
            font-size: 14pt;
            y: 15px;
        }

        configure := Rectangle {
            width: 80%;
            height: 80%;

            conf_text := Text {
                text: "Configure";
                font-size: 12pt;
                y: 0px;
            }

            ScrollView {
                height: configure.height - conf_text.height - conf_text.y - 25px;
                y: conf_text.y + 25px;
                vert := VerticalLayout {
                    alignment: start;
                    spacing: 10px;
                    Text {
                        text: "Mods";
                        font-size: 11pt;
                    }
                    for mod[i] in Info.recommended_mod_list: CheckBox {
                        text: mod;
                        checked: Info.recommended_mods_toggle[i];
                        toggled => {
                            Info.recommended_mods_toggle[i] = self.checked;
                        }
                    }

                    SeparatorLine {}

                    Text {
                        text: "JVM";
                        font-size: 11pt;
                    }
                    for jvm[i] in Info.jvms: CheckBox {
                        text: jvm;
                        checked: Info.jvms_toggle[i];
                        toggled => {
                            Info.jvms_toggle[i] = self.checked;
                        }
                    }

                    SeparatorLine {}

                    Text {
                        text: "Garbage Collector";
                        font-size: 11pt;
                    }
                    for gc[i] in Info.gcs: CheckBox {
                        text: gc;
                        checked: Info.gcs_toggle[i];
                        toggled => {
                            Info.gcs_toggle[i] = self.checked;
                        }
                    }
                    
                    SeparatorLine {}

                    Text {
                        text: "JVM Arguments";
                        font-size: 11pt;
                    }
                    for arg[i] in Info.args: CheckBox {
                        text: arg;
                        checked: Info.args_toggle[i];
                        toggled => {
                            Info.args_toggle[i] = self.checked;
                        }
                    }

                    SeparatorLine {}

                    Text {
                        text: "Memory Allocated (GiB)";
                    }
                    HorizontalLayout {
                        Text {
                            text: Info.ram_alloc;
                        }
                        Slider {
                            width: 90%;
                            maximum: Info.memory_capacity_mib / 1024;
                            minimum: 1;
                            step: 1;
                            changed(value) => {
                                Info.ram_alloc = value;
                            }
                        }
                    }
                    
                    SeparatorLine {}
                }
            }
        }
        Button {
            text: "Run Benchmark";
            y: configure.y + configure.height;
            clicked => {}
        }
    }
}